# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d14b3ccbd93e47e46e5e9e86b32467e7"
application_url = "https://conf-oman-hiv-press.trycloudflare.com"
embedded = true
name = "WorkOrder"
handle = "workorder"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://conf-oman-hiv-press.trycloudflare.com/auth/callback",
  "https://conf-oman-hiv-press.trycloudflare.com/auth/shopify/callback",
  "https://conf-oman-hiv-press.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
